//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blath3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliacao
    {
        public int AvaliacaoId { get; set; }
        public int UsuarioId { get; set; }
        public int EmpresaId { get; set; }
        public Nullable<decimal> Nota { get; set; }
        public string Descricao { get; set; }
        public Nullable<bool> Aprovado { get; set; }
        public Nullable<int> PedEmpId { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public Nullable<System.DateTime> AtualizadoEm { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual PedEmp PedEmp { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
