//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blath3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatSub
    {
        public int CatSubId { get; set; }
        public Nullable<int> CategoriaId { get; set; }
        public Nullable<int> SubcategoriaId { get; set; }
        public string Tema { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public Nullable<System.DateTime> AtualizadoEm { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Subcategoria Subcategoria { get; set; }
    }
}
