//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blath3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedEmp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedEmp()
        {
            this.PedEmpChats = new HashSet<PedEmpChat>();
            this.Avaliacaos = new HashSet<Avaliacao>();
        }
    
        public int PedEmpId { get; set; }
        public Nullable<int> PedidoId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public Nullable<System.DateTime> AtualizadoEm { get; set; }
        public string StatusResposta { get; set; }
        public Nullable<decimal> Cotacao { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedEmpChat> PedEmpChats { get; set; }
        public virtual Pedido Pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avaliacao> Avaliacaos { get; set; }
    }
}
