//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blath3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.PedEmps = new HashSet<PedEmp>();
        }
    
        public int PedidoId { get; set; }
        public Nullable<System.Guid> PedidoCode { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> SubcategoriaId { get; set; }
        public string Descricao { get; set; }
        public string Periodo { get; set; }
        public string Local { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public Nullable<System.DateTime> AtualizadoEm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedEmp> PedEmps { get; set; }
        public virtual Subcategoria Subcategoria { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
